### PR TITLE
128 organizer would like to vote too

### PR DESCRIPTION
**Pull request by SponsoredByPuma**

### CODE REVIEW

**Comment by SponsoredByPuma** [comment]
I'll turn this into a Pull Request as soon as I finished all the tests.

**Review by stritti — APPROVED** [review]

**Comment by KzuDemEvin** [comment]
Hi @SponsoredByPuma,

at start-up the backend throws an error in class `SessionsScheduldedTasks.java` in method `deleteOldSessions`. The error:
`Failed to instantiate io.diveni.backend.model.Session using constructor public io.diveni.backend.model.Session`.

There is also an error when trying to create a session:
`Parameter hostVoting must not be null!`
Payload: `{
    "set": [
        "1",
        "2",
        "3",
        "5",
        "8",
        "13",
        "21"
    ],
    "timerSeconds": 30,
    "password": null,
    "userStories": [],
    "userStoryMode": "NO_US"
}`


Is there any configuration needed? I only checked out your branch. Feel free to ask for information if you need some.

**Comment by KzuDemEvin** [comment]
> Make sure all of your Sessions are deleted in the databaseService. This error occurs when there are still some session in your database, which dont have the hostVoting attribute.

Yes, that seemed to be the problem. Thanks!

**Review by KzuDemEvin — COMMENTED** [review]
## I have a few points to discuss here:
- There are two ways to enable host voting: while creating a session and while beeing in a session. In my opinion it would be enough to be able to enable it while preparing.
- Is there a way to use the planning poker cards as a host to vote? Currently the buttons from the prepare sessions are used.


### I also found a bug:
1. Create a session with at least 1 member
2. Start the session
3. Select only one estimator as host
4. Click on "Show result"

--> The host does not see the estimation he picked. Only the members can see it

--------
What do you think about my points?

**Comment by SponsoredByPuma** [comment]
Hi @KzuDemEvin,
I also placed the button on the session page, since you usually tend to rush throught the prepare page (at least i do 😆). Which results in forgetting to switch on the host voting option. That way you still have the flexibility to switch it on in the session page.

Also I used the buttons from the prepare page, because i thought that if you take the usual cards the admin could not see his stats. For example if a member finishes or the show results button. (At least the focus wouldn't be the biggest anymore)

I guess we could try to use the cards but maybe we should downsize them ? But then again the cards would be quite small or the admin couldnt see all of his stats at once. Please let me know if you have another idea to implement the cards on the session page. 😄

**Comment by stritti** [comment]
@SponsoredByPuma could you resolve the merge conflicts, please?

**Comment by stritti** [comment]
@SponsoredByPuma could you resolve merge conflicts please?

**Comment by SponsoredByPuma** [comment]
I resolved the conflicts, but we need two new Icons.
image
The five is missing for the dark mode and light mode

**Pull request merged**
