### PR TITLE
GraalVM for more performant backend images

### PR DESCRIPTION
**Pull request by Harsh3305**
close https://github.com/Sybit-Education/Diveni/issues/422

### CODE REVIEW

**Comment by Harsh3305** [comment]
Hi @SponsoredByPuma 👋🏻 
Can you review my PR.
Thanks

**Comment by SponsoredByPuma** [comment]
Yeah, sure I will look into this the next following days

**Comment by SponsoredByPuma** [comment]
Hi @Harsh3305,
I looked over your PR and it looks good.
I've just got a problem trying to run it on my machine, maybe you could help me out there.
Everytime i try to run it I get this error: 
image
What could I do to fix this?

**Comment by Dan1elBox** [comment]
I receive the same error as @SponsoredByPuma .
Could this possibly be due to all GraalVM images now being on GHCR?

See: https://github.com/graalvm/container/pkgs/container/graalvm-ce 
We might need to change `oracle/graalvm-ce:latest` to, for example, `ghcr.io/graalvm/graalvm-ce:ol8-java17`.

**Comment by Harsh3305** [comment]
Hi @SponsoredByPuma @Dan1elBox 
Done some changes in dockerfile. Please review 😄

**Comment by SponsoredByPuma** [comment]
Hi @Harsh3305,
the issue is now fixed. Currently I get an error message at the last step: 
image
Which command are you using to start the docker?

**Comment by Dan1elBox** [comment]
Hi @Harsh3305 
The image now loads correctly, but I'm encountering the same error as @SponsoredByPuma, indicating that I should specify the class with the main entry point method.

**Comment by stritti** [comment]
> Hi @Harsh3305,
> 
> is there any performance gain at all with GraalVM over Docker?

@KzuDemEvin GraalVM is created especially for container environments and requires less space and startup overhead - as I know.

**Comment by Dan1elBox** [comment]
Hi @Harsh3305, thank you for your interest and contribution to this project 😃 
Do you plan to continue working on this PR in the future?"

**Pull request closed without merging**
