### PR TITLE
Add feedback button and translation

### PR DESCRIPTION
**Pull request by Valeri12580**
Add feedback btn to the footer.

### CODE REVIEW

**Comment by SponsoredByPuma** [comment]
Looks good to me. But could you remove the translations? We only the english one. The rest will be added through CrowdIn

**Comment by Valeri12580** [comment]
> Looks good to me. But could you remove the translations? We only the english one. The rest will be added through CrowdIn

Done :)

**Review by stritti — APPROVED** [review]

**Comment by stritti** [comment]
Great work, @Valeri12580. Could we make it a bit more visible? Something like a fixed area at the right border of browser? 

I found something on Google. something like following? What do you think?
image

**Comment by Valeri12580** [comment]
> Great work, @Valeri12580. Could we make it a bit more visible? Something like a fixed area at the right border of browser?
> 
> I found something on Google. something like following? What do you think? image

Nice idea @stritti , I will implement it

**Comment by Valeri12580** [comment]
@stritti  I changed the button style. What do you think?

**White theme**
image

**Black theme**
image

**Comment by stritti** [comment]
Awesome, @Valeri12580! Really nice solution!

**Comment by stritti** [comment]
I think you should push at least your design update, @Valeri12580 ...

**Comment by Valeri12580** [comment]
I pushed the latest changes, @stritti

**Review by stritti — APPROVED** [review]

**Comment by stritti** [comment]
Thank you very much for the improvements @Valeri12580 !

**Pull request merged**
