### PR TITLE
Issue229 show result on last vote

### PR DESCRIPTION
**Pull request by sourabhkashyap95**

### CODE REVIEW

**Comment by stritti** [comment]
Thank you very much @sourabhkashyap95 for your improvement. I tested on my test environment, but the clients are not notified about the voting is ended.
`checkIfAllMembersVoted` seems to be correct, but the notification via websocket seems not working in correct way.

**Comment by sourabhkashyap95** [comment]
Hi @stritti will check this and will revert back with working PR.

**Comment by sourabhkashyap95** [comment]
Hi @stritti, I have one question, is it required for admin also to display votes once everyone is done with voting or we can display votes as soon as member is done with his/her vote

**Comment by sourabhkashyap95** [comment]
Will raise a new PR with final changes after fix.

**Pull request closed without merging**
