### PR TITLE
Migrate from SpringFox to SpringDoc.

### PR DESCRIPTION
**Pull request by christian-german**
Update gradle dependencies
Remove unnecessary old springfox config files.

Fix #206

### CODE REVIEW

**Comment by KzuDemEvin** [comment]
Hi @christian-german,
thank you for your work!

I saw that the workflow failed, because it tried to push something onto a branch which is non existend.
* Refer: #236 

I merged the changes into your repo.

**Comment by christian-german** [comment]
Hi @KzuDemEvin ,

Yes, I've seen that. Nice fix.

Cheers,
Christian

**Comment by stritti** [comment]
@christian-german is the URL of Swagger still the same? probably we have to update the docs too: https://github.com/Sybit-Education/Diveni/blob/main/docs/guide/architecture.md#rest-api

**Comment by christian-german** [comment]
Hi @stritti ,

Indeed, the url has changed.
Let me update the PR.

Christian

**Comment by christian-german** [comment]
Hey @stritti ,

Actually, spring-fox was in v3 before the move to spring-doc. Therefore, the URL to access the UI is the same.
I've just updated the architecture.md documentation to remove the reference to the spring-fox configuration.

The branch has also been rebased against main to avoid any conflict.

Cheers,
Christian.

**Comment by stritti** [comment]
Great work, @christian-german! Thank you very much for helping to improve Diveni ❤️

**Pull request merged**
