### PR TITLE
Long Description ruins layout

### PR DESCRIPTION
**Pull request by SponsoredByPuma**
removed viewer in markdown & added text area

### CODE REVIEW

**Comment by SponsoredByPuma** [comment]
It looks like this now: 
image

**Comment by Dan1elBox** [comment]
I'm not sure if I'm doing something wrong, but when inserting a story as a session admin, only the title is displayed for the member, while the description remains empty. See the following image:
NoDescription


Tested in a local setup with Firefox v.118.0.2, Chrome v.118.0.5993.70, and Edge v.117.0.2045.60
Node:  v18.17.1

**Comment by SponsoredByPuma** [comment]
This is because this Pull Request is based on an older state of Diveni, which didnt implement the functionality of sending the description to all of the users.

**Comment by Dan1elBox** [comment]
@SponsoredByPuma All right, didn't realize that the PR is not up to date anymore 🙈.
Now, after the update, everything looks good so far.

**Review by Dan1elBox — APPROVED** [review]

**Pull request merged**
