### PR TITLE
#179 auto-select user story when active

### PR DESCRIPTION
**Pull request by KzuDemEvin**
# Feature request #179 

## What
* By clicking on the desired user story, the host can select the active user story for all members in the same session
* This feature is disabled in the lobby and is only enabled while planning
* Members are still able to view all user stories

## Preview
* Left side: Host
* Right side: Member

UserStorySelect

Edit: Add preview

### CODE REVIEW

**Comment by stritti** [comment]
Looks really great. Very helpful.

Could you extend it to mark the selected story in a way although the voter switches to another story to find it again?

**Comment by KzuDemEvin** [comment]
> Could you extend it to mark the selected story in a way although the voter switches to another story to find it again?

Nice suggestion!

I added the changes to the PR.
UserStorySelect

* Blue: Current active story
* Green: The story the host has selected

**Comment by KzuDemEvin** [comment]
Update: Now with a leading icon instead of a different color for the currently active user story

* Left side: Host
* Right side: Member

UserStorySelect

**Review by SponsoredByPuma — APPROVED** [review]

**Review by SponsoredByPuma — APPROVED** [review]
Looks good to me

**Pull request merged**
