### PR TITLE
Upgrade dependencies for the purpose of migration to Vue 3

### PR DESCRIPTION
**Pull request by ravihidayat**
I had to start again since my Ubuntu broke. So I was thinking, it would be great to log updates here as suggested by @stritti. I have upgraded relevant dependencies but seems like there are issues with peer dependencies after running `npm install`. Here is the log:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: diveni-frontend@1.0.0
npm ERR! Found: vue@2.7.10
npm ERR! node_modules/vue
npm ERR!   vue@"^3.1.0" from the root project
npm ERR!   peer vue@"^2.5.0" from @toast-ui/vue-editor@3.2.0
npm ERR!   node_modules/@toast-ui/vue-editor
npm ERR!     @toast-ui/vue-editor@"^3.2.0" from the root project
npm ERR!   9 more (@vue/babel-preset-app, @vue/babel-preset-jsx, ...)        
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @vue/compat@"^3.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@3.2.41
npm ERR! node_modules/vue
npm ERR!   peer vue@"3.2.41" from @vue/compat@3.2.41
npm ERR!   node_modules/@vue/compat
npm ERR!     @vue/compat@"^3.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

What I did to make the migration work is by adding `--legacy-peer-deps` after `npm install`.

### CODE REVIEW

**Comment by ravihidayat** [comment]
Todo:

1. Fix errors and warnings
2. Replace BootstrapVue with PrimeVue

**Comment by stritti** [comment]
There are some other deps which are also not supporting by vue3 😔

* @toast-ui/vue-editor: https://github.com/nhn/tui.editor/issues/1325 -> PrimeVue misses Markdown-Editor too: https://github.com/primefaces/primevue/issues/437
* vue2-interact: https://github.com/mateuszRybczonek/vue2-interact/issues/27

**Comment by stritti** [comment]
@ravihidayat I created an PR on your branch with some additional changes: https://github.com/ravihidayat/Diveni/pull/1

**Comment by stritti** [comment]
@ravihidayat to do one step after the other I am thinking about 

- First migrate to vue3 and use https://github.com/cdmoro/bootstrap-vue-3
- If vue3 is working, we could migrate from Boostrap to PrimeVue

what do you think, @ravihidayat ?

**Pull request closed without merging**
